apiVersion: v1
kind: Service
metadata:
  labels:
    role: deepthought-h2-database
  name: deepthought-h2-database
spec:
  ports:
  - name: deepthought-h2-database
    port: 1521
  - name: deepthought-h2-database-http
    port: 81
  selector:
    role: deepthought-h2-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: deepthought-h2-database
  name: deepthought-h2-database
spec:
  replicas: 1
  selector:
    matchLabels:
      role: deepthought-h2-database
  template:
    metadata:
      labels:
        role: deepthought-h2-database
      name: deepthought-h2-database
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: deepthought-h2-database-environment-variables
        image: cdrsandbox/deepthought-h2-database:20200916
        imagePullPolicy: Always
        name: deepthought-h2-database
        ports:
        - containerPort: 1521
        - containerPort: 81
        resources:
          limits:
            cpu: "0.5"
            memory: 0.75Gi
          requests:
            cpu: "0.25"
            memory: 0.5Gi

