kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../01-standalone/cdrregister
- ../01-standalone/pingdirectory
- ../01-standalone/pingfederate-cluster
- ../01-standalone/pingaccess-admin
- ../01-standalone/pingaccess
- ../01-standalone/deepthought-admin-service
- ../01-standalone/deepthought-bank-api
- ../01-standalone/deepthought-h2-database
- ../01-standalone/cdr-dr-client
- ../01-standalone/agentless-consentapp
- ../01-standalone/mock-dh-api
- ../01-standalone/pingdatasync


# The only difference in standalone deployments vs "fullstack" (integrated) is the product configurations. 
# here we replace standalone server-profiles ("getting-started") with "baseline" for each product

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cdrregister-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.cdrregister
- name: pingdirectory-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.pingdirectory
- name: pingfederate-admin-environment-variables
  behavior: replace
  envs:
    - devops
    - pf.env
    - env_vars.common
    - env_vars.pingfederate-admin
- name: pingfederate-engine-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.pingfederate-engine
- name: pingaccess-admin-environment-variables
  behavior: replace
  envs:
    - devops
    - pa.env
    - env_vars.common
    - env_vars.pingaccess-admin
- name: pingaccess-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.pingaccess
- name: deepthought-admin-service-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.deepthought-admin-service
- name: deepthought-bank-api-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.deepthought-bank-api
- name: deepthought-h2-database-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.deepthought-h2-database
- name: cdr-dr-client-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.cdr-dr-client
- name: agentless-consentapp-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.agentless-consentapp
- name: mock-dh-api-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.mock-dh-api
- name: pingdatasync-environment-variables
  behavior: replace
  envs:
    - devops
    - env_vars.common
    - env_vars.pingdatasync

patches:
- target:
    kind: StatefulSet
    name: ^pingdirectory$
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: ^pingaccess$
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: ^pingfederate$
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: ^cdr-dr-client$
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: cdrsandbox/sample-dr-client:20200916
