apiVersion: v1
kind: Service
metadata:
  labels:
    role: mock-dh-api
  name: mock-dh-api
spec:
  ports:
  - name: mock-dh-api
    port: 6879
    targetPort: 6879
  selector:
    role: mock-dh-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: mock-dh-api
  name: mock-dh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mock-dh-api
  template:
    metadata:
      labels:
        role: mock-dh-api
      name: mock-dh-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mock-dh-api-environment-variables
        image: cdrsandbox/mock-dh-apis:20201203_1
        imagePullPolicy: Always
        name: mock-dh-api
        ports:
        - containerPort: 6879
        resources:
          limits:
            cpu: "1"
            memory: 0.5Gi
          requests:
            cpu: "0.5"
            memory: 0.25Gi
