apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingaccess
  name: pingaccess
spec:
  ports:
  - name: pa-app
    port: 443
    targetPort: 3000
  - name: pa-internal
    port: 3000
  selector:
    role: pingaccess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingaccess
  name: pingaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingaccess
  template:
    metadata:
      labels:
        role: pingaccess
      name: pingaccess
    spec:
      initContainers:
      - name: init
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingaccess-admin:9090 ; do echo waiting for admin ; sleep 3 ; done']
      containers:
      - envFrom:
        - configMapRef:
            name: pingaccess-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingaccess:6.0.0-alpine-edge
        imagePullPolicy: Always
        name: pingaccess
        ports:
        - containerPort: 443
        - containerPort: 3000
#        resources:
#          limits:
#            cpu: "1"
#            memory: 1.5Gi
#          requests:
#            cpu: "1"
#            memory: 1.5Gi
