version: "3.1"

services:
  pingaccess:
    image: pingidentity/pingaccess:6.1.3-edge
    command: wait-for pingfederate:9031 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingaccess
      - LICENSE_VERSION=6.0
      - PA_POST_CONFIGURATION_DELAY=0
      - OPERATIONAL_MODE=STANDALONE
      - PA_ADMIN_PORT=9000
      - PA_LIMIT_REQUEST_LINE=40960
    env_file:
      - ~/.pingidentity/devops
      - pa.env
      - cdr.env
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/full-stack.pingaccess:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingaccess:/opt/in
    ports:
      - 443:3000
      - 80:7080
      - 9000:9000
      - 9001:9001
    networks:
      - pingnet-dmz
      - pingnet-internal

  agentless-consentapp:
    image: cdrsandbox/agentless-consentapp:20201026
#    command: /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 8082:7879
    networks:
      - pingnet-internal
      - pingnet-dmz

  pingfederate:
    image: pingidentity/pingfederate:10.1.3-edge
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingfederate
    env_file:
      - ~/.pingidentity/devops
      - pf.env
      - cdr.env
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
    #volumes:
    #  - ./pingfederate-out:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory:8.1.0.2-edge
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingdirectory
      #- SERVER_PROFILE_BRANCH=2001
      - MAKELDIF_USERS=10
      #- VERBOSE=true
      - MAX_HEAP_SIZE=768m
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 1636:636
      - 1443:443
      - 389:389
    networks:
      - pingnet-internal

  cdr-dr-client:
    image: cdrsandbox/sample-dr-client:20200916
    command: /tmp/wait-for pingdirectory:389 -t 900 -- /tmp/wait-for pingaccess:3000 -t 900 -- /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/datarecipient/internal/config
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 8080:7878
    networks:
      - pingnet-internal
      - pingnet-dmz

  cdrregister:
    image: cdrsandbox/mock-register:20201102
    #command: /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/mock-cdrregister-config/cache
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 8084:8084
    networks:
      - pingnet-internal
      - pingnet-dmz
    volumes:
       - ${HOME}/projects/devops/volumes/cdr.mockregister:/tmp/cache

  deepthought-bank-api:
    image: cdrsandbox/deepthought-bank-api-service:20200916
    environment:
  #    - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/datarecipient-config/config
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 8090:8081
    networks:
      - pingnet-internal
      - pingnet-dmz

  deepthought-admin-service:
    image: cdrsandbox/deepthought-admin-service:20200916
    environment:
  #    - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/datarecipient-config/config
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 8088:8080
    networks:
      - pingnet-internal
      - pingnet-dmz

  deepthought-h2-database:
    image: cdrsandbox/deepthought-h2-database:20200916
    environment:
      - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/datarecipient-config/config
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 1521:1521
      - 81:81
    networks:
      - pingnet-internal
      - pingnet-dmz

#  pingdataconsole:
#    image: pingidentity/pingdataconsole:edge
#    ports:
#      - "8443:8443"
#    networks:
#      - pingnet-internal
#      - pingnet-dmz

networks:
    pingnet-internal:
    pingnet-dmz:
