version: "3.4"

services:
  pingaccess:
    image: pingidentity/pingaccess:6.2.0-edge
    command: wait-for pingfederate:9031 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingaccess
      - LICENSE_VERSION=6.0
      - PA_POST_CONFIGURATION_DELAY=0
      - OPERATIONAL_MODE=STANDALONE
      - PA_ADMIN_PORT=9000
      - PA_LIMIT_REQUEST_LINE=40960
    env_file:
      - ~/.pingidentity/devops
      - pa.env
      - cdr.env
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/full-stack.pingaccess:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingaccess:/opt/in
    ports:
      - 6443:6443
      - 3000:443
      - 443:3000
      - 80:7080
      - 9000:9000
      - 9001:9001
    expose:
      - 443
    networks:
      - pingnet-internal

  agentless-consentapp:
    image: cdrsandbox/agentless-consentapp:20210222
#    command: /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    links:
      - "pingaccess:sso.data-holder.local"
      - "pingaccess:mockregister.data-holder.local"
      - "pingaccess:pd.data-holder.local"
      - "pingaccess:api.data-holder.local"
    ports:
      - 8082:7879
    networks:
      - pingnet-internal

  mock-dh-api:
    image: cdrsandbox/mock-dh-apis:20210202
#    command: /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    links:
      - "pingaccess:sso.data-holder.local"
      - "pingaccess:mockregister.data-holder.local"
      - "pingaccess:pd.data-holder.local"
      - "pingaccess:api.data-holder.local"
    ports:
      - 6879:6879
    networks:
      - pingnet-internal

  pingfederate:
    image: pingidentity/pingfederate:10.2.1-edge
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingfederate
    env_file:
      - ~/.pingidentity/devops
      - pf.env
      - cdr.env
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-internal
    cap_add:
      - NET_ADMIN
    links:
      - "pingaccess:sso.data-holder.local"
      - "pingaccess:mockregister.data-holder.local"
      - "pingaccess:pd.data-holder.local"
      - "pingaccess:api.data-holder.local"
    #volumes:
    #  - ./pingfederate-out:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory:8.2.0.1-edge
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingdirectory
      #- SERVER_PROFILE_BRANCH=2001
      - MAKELDIF_USERS=10
      #- VERBOSE=true
      - MAX_HEAP_SIZE=768m
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    links:
      - "pingaccess:sso.data-holder.local"
      - "pingaccess:mockregister.data-holder.local"
      - "pingaccess:pd.data-holder.local"
      - "pingaccess:api.data-holder.local"
    ports:
      - 3443:443
      - 3389:389
      - 3636:636
      - 1636:636
      - 1443:443
      - 389:389
    networks:
      - pingnet-internal

  pingdatasync:
    image: pingidentity/pingdatasync:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=server_profiles/pingdatasync
    env_file:
      - ${HOME}/.pingidentity/devops
      - cdr.env
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    links:
      - "pingaccess:sso.data-holder.local"
      - "pingaccess:mockregister.data-holder.local"
      - "pingaccess:pd.data-holder.local"
      - "pingaccess:api.data-holder.local"
    ports:
      - "2636:636"
      - "2443:443"
    networks:
      - pingnet-internal

  cdr-dr-client:
    image: cdrsandbox/sample-dr-client:20210222
    command: /tmp/wait-for pingdirectory:389 -t 900 -- /tmp/wait-for pingaccess:443 -t 900 -- /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/datarecipient/internal/config
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    links:
      - "pingaccess:sso.data-holder.local"
      - "pingaccess:mockregister.data-holder.local"
      - "pingaccess:pd.data-holder.local"
      - "pingaccess:api.data-holder.local"
    ports:
      - 8080:7878
    networks:
      - pingnet-internal

  cdrregister:
    image: cdrsandbox/cdr-register-testharness:20210225
    #command: /tmp/hooks/start-service.sh
    environment:
      - VERBOSE=true
      - SERVER_PROFILE_PATH=server_profiles/mock-cdrregister-config/cache
    env_file:
      - ~/.pingidentity/devops
      - cdr.env
    ports:
      - 8084:8084
    networks:
      - pingnet-internal
    volumes:
       - ${HOME}/projects/devops/volumes/cdr.mockregister.20210225:/tmp/cache


  pingdatagovernance:
    image: pingidentity/pingdatagovernance:8.2.0.1-edge
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-cdr-sandbox.git
      - SERVER_PROFILE_PATH=server_profiles/pingdatagovernance
    env_file:
      - ${HOME}/.pingidentity/devops
      - cdr.env
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9080:80"
      - "7443:443"
    networks:
      - pingnet-internal

  pingdatagovernancepap:
    image: pingidentity/pingdatagovernancepap:8.2.0.1-edge
    # command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-cdr-sandbox.git
      - SERVER_PROFILE_PATH=server_profiles/pingdatagovernancepap
      - HTTPS_PORT=8443
    env_file:
      - ${HOME}/.pingidentity/devops
      - cdr.env
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8443:8443"
    networks:
      - pingnet-internal
    #volumes:
    #  - ./pingdatagovernancepap-out:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/pdg-pap-integration/pingdatagovernancepap:/opt/in

  data-in-spa:
    image: cdrsandbox/data-in-spa:20210225
    ports:
      - "8686:80"
    networks:
      - pingnet-internal

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - "9443:8443"
    networks:
      - pingnet-internal

  datain-configurepf:
    image: cdrsandbox/datain-configure-pf:20210225
    command: /tmp/wait-for pingdirectory:389 -t 900 -- /tmp/wait-for pingaccess:443 -t 900 -- /tmp/hooks/start-service.sh
    env_file:
      - cdr.env
    networks:
      - pingnet-internal

networks:
    pingnet-internal:
