apiVersion: v1
kind: Service
metadata:
  labels:
    role: cdrregister
  name: cdrregister
spec:
  ports:
  - name: cdrregister
    port: 8084
  selector:
    role: cdrregister
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: cdrregister
  name: cdrregister
spec:
  replicas: 1
  selector:
    matchLabels:
      role: cdrregister
  template:
    metadata:
      labels:
        role: cdrregister
      name: cdrregister
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cdrregister-environment-variables
        image: gcr.io/ping-identity/cdr-au/mock-register:20200803
        imagePullPolicy: Always
        name: cdrregister
        ports:
        - containerPort: 8084
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi

