apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  ports:
  - name: ldaps
    port: 636
  - name: ssl
    port: 443
  - name: ldap
    port: 389
  selector:
    role: pingdatagovernance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdatagovernance
  template:
    metadata:
      labels:
        role: pingdatagovernance
      name: pingdatagovernance
    spec:
      initContainers:
      - name: init
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingdirectory ; do echo waiting for admin ; sleep 3 ; done']
      containers:
      - name: pingdatagovernance
        envFrom:
          - configMapRef:
              name: pingdatagovernance-environment-variables
          - secretRef:
              name: devops-secret
              optional: true
        image: pingidentity/pingdatagovernance:edge
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /preStop.sh
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 60
        name: pingdatagovernance
        ports:
        - containerPort: 636
        - containerPort: 443
        - containerPort: 389
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      terminationGracePeriodSeconds: 300
