apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: getting-started/pingdatasync
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
kind: ConfigMap
metadata:
  labels:
    role: pingdatasync
  name: pingdatasync-environment-variables
