kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../01-standalone/pingaccess-admin

# The only difference in standalone deployments vs "fullstack" (integrated) is the product configurations. 
# here we replace standalone server-profiles ("getting-started") with "baseline" for each product

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-admin-environment-variables
  behavior: replace
  envs:
    - env_vars.pingaccess-admin

patches:
- target:
    kind: Deployment
    name: ^pingaccess-admin$
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: gcr.io/ping-identity/cdr-au/pingaccess-6.1:20200625

