apiVersion: v1
kind: Service
metadata:
  labels:
    role: agentless-consentapp
  name: agentless-consentapp
spec:
  ports:
  - name: agentless-consentapp
    port: 7879
    targetPort: 7879
  selector:
    role: agentless-consentapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: agentless-consentapp
  name: agentless-consentapp
spec:
  replicas: 1
  selector:
    matchLabels:
      role: agentless-consentapp
  template:
    metadata:
      labels:
        role: agentless-consentapp
      name: agentless-consentapp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: agentless-consentapp-environment-variables
        image: cdrsandbox/agentless-consentapp:20201026
        imagePullPolicy: Always
        name: agentless-consentapp
        ports:
        - containerPort: 7879
        resources:
          limits:
            cpu: "1"
            memory: 0.5Gi
          requests:
            cpu: "0.5"
            memory: 0.25Gi
