deepthought:
  version: 1.0.0
server:
  port: 8081
  servlet:
    context-path: /cds-au
spring:
   datasource:
     url: jdbc:h2:tcp://deepthought-h2-database:1521/deepthought;USER=sa
     driverClassName: org.h2.Driver
   jpa:
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: non_empty
